### ISSUE TITLE
AttributeError in nicoletta.py

### ISSUE THREAD

**Issue by barnumbirr** [ralsina/nicoletta#2]
Traceback (most recent call last):
  File "nicoletta.py", line 57, in <module>
    main()
  File "nicoletta.py", line 47, in main
    outf.write(render('page.tmpl', tpl_data, content=render_post(posts[-1])))
  File "nicoletta.py", line 39, in render_post
    return templates['post.tmpl'].safe_substitute(post.**dict**, text=markdown(post.text))
AttributeError: 'Post' object has no attribute '**dict**'

**Comment by ralsina** [comment]
Is that python 3?

**Comment by barnumbirr** [comment]
Nope, it is

```
Python 2.7.5 (default, Mar  9 2014, 22:15:05)
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
```

Thank you for looking into this.
Cheers.

**Comment by barnumbirr** [comment]
Hi there,

do you have some news on this issue? I've done some investigating myself but I somehow could not find what's wrong. Thank you.

Cheers.
